config/routes.rb
Rails.application.routes.draw do

  resources :people, except: [:show]

  root to: "people#index"
  end

app/models/person.rb
class Person
  include Mongoid::Document
  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :notes, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path, notice: "The person has been created!" and return
    end
    render 'new'
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update_attributes(person_params)
      redirect_to people_path, notice: "#{first_name} #{last_name} has been updated!" and return
    end

    render 'edit'
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    redirect_to people_path, notice: "#{first_name} #{last_name} has been deleted!" and return
  end
private
  def person_params
    params.require(:person).permit(:first_name, :last_name, :email, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MongoDBExampleApp</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
	<div class="form-group">
		<%= f.label :first_name %>
		<%= f.text_field :first_name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :last_name %>
		<%= f.text_field :last_name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :notes %>
		<%= f.text_area :notes, class: "form-control" %>
	</div>
	<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/people/edit.html.erb
<h1>New Person</h1>
<div class="well">
	<%= render "form" %>
</div>

app/views/people/index.html.erb
<h1>People</h1>
<div class="well">
	<%= link_to "New Person", new_person_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
	<div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Notes</th>
			<th>&nbsp;</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
		<% if @people.size == 0 %>
			<tr>
				<td colspan="6">No people found.</td>
			</tr>
		<% else %>
			<% @people.each do |person| %>
				<tr>
					<td><%= person.first_name %></td>
					<td><%= person.last_name %></td>
					<td><%= person.email %></td>
					<td><%= person.notes %></td>
					<td>
						<%= link_to "Edit", edit_person_path(person), class: "btn btn-default" %>
					</td>
					<td>
						<%= button_to "Delete", person, method: :delete, data: { confirm: "Are you sure you wish to delete #{person.first_name} #{person.last_name}?" }, class: "btn btn-danger" %>
					</td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/people/new.html.erb
<h1>New Person</h1>
<div class="well">
	<%= render "form" %>
</div>